version: "3"
services:
    pypi:
        image: pef/pypi
        volumes:
            - ~/pypi:/srv/pypi:rw
        ports:
            - 8080:80

    db:
        image: pef/mariadb5
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=employee
            - MYSQL_USER=employee
            - MYSQL_PASSWORD=password
        ports:
            - "13306:3306"

    main:
        image: pef/python3
        depends_on:
            - pypi
        command: "/code/build.sh"
        volumes:
            - ./src/main/python:/code

    test:
        image: pef/python3
        depends_on:
            - pypi
            - db
        command: "/code/test.sh"
        volumes:
             - ./src/test/python:/code
        environment:
            - PIP_EXTRA_INDEX_URL=http://pypi:80/

    # can't build app here as pypi does not get started during a build
    # need to have pypi running and use standard Docker build
    #    app:
    #        depends_on:
    #            - pypi
    #        image: pef/pefspikeapp
    #        volumes:
    #            - ./src/app/python:/code
