version: "3"
services:
    jupyterlab:
        image: pef/jupyterlab_scipy
        volumes:
            - ${PWD}/src:/home/jovyan/work:rw
        ports:
            - 8888:8888
        command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888" ]
