version: "3"
services:
    pypi:
        image: pef/pypi
        volumes:
            - ~/pypi:/srv/pypi:rw
        ports:
            - 8080:80

    behave:
        depends_on:
            - pypi
        image: pef/python3
        command: "behave src/test/python/features"
        volumes:
            - .:/code
        environment:
            - PYTHONPATH=/code/src/main/python:/code/src/test/python
            - PIP_EXTRA_INDEX_URL=http://pypi:80/simple/

    pytest:
        image: pef/python3
        command: "pytest -v"
        volumes:
            - .:/code
        environment:
            - PYTHONPATH=/code/src/main/python:/code/src/test/python
            - PIP_EXTRA_INDEX_URL=http://pypi:80/simple/

    main:
        image: pef/python3
        depends_on:
            - pypi
        command: "/code/upload_internal.sh"
        volumes:
            - ./src/main/python:/code

    test:
        image: pef/python3
        depends_on:
            - pypi
        command: "/code/src/test/python/test.sh"
        volumes:
            - .:/code
#            - ./src/test/python:/code
#            - ./src/test/env:/code/env
        environment:
            - PIP_EXTRA_INDEX_URL=http://pypi:80/simple/
